services:
  db:
    image: postgres:15-alpine
    volumes:
      - ${DEV_DATA_PATH:-./data}/postgres:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${DEV_DATA_PATH:-./data}/elasticsearch:/usr/share/elasticsearch/data
    user: "1000:1000"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
  elasticsearch_data_dev: 